@startuml まとめ
!theme sketchy-outline

class 利用者プロパティ{
}

class 未所属{
    天候
    季節
    時間帯
    発展度
    sincos()
}

Class 速度{
到着必要時間：固定
到着までの距離：固定
速度(時速)=距離/時間
速度x時間の面積を固定ベジェ速度算出()

}



class 路線図 {
    位置表示()
}
class 路線 {
    発車駅
    次駅
駅間距離(stStation_id,endStation_id)
    発展度
}
class カレンダー{
    flg動的
    時間速度
    日数ステップ
    月ステップ
    get日時()
    get季節()
}
class 時刻表{
    位置管理()
    時刻管理()
}

class 電車 {
    電車ID
    電車高さ
    車種
    車両数
駅間位置
}

class 人 {
    視点位置
    位置
    電車ID
}


class 駅 {
    駅高さ
    flg_terminal
    駅到着判定(=発車駅&terminal：読上無し else terminal：終点アナウンス)
    終点(たざわんが、乗り換えを聞き、入力促す。登場駅は自由、乗換は限定)
}

package オブジェクト{
class 背景{
    天候()
    季節()
    時間帯()
}



'各風景 駅舎 建築物
class オブジェクト{
    オブジェクトID
    頻度
    表示高さ
    SCRL速度
    表現切替()
    表示切替GEOFixed/Free()
}
class 駅舎{}
class 踏切{}
class 車庫{}

}

@enduml
